### ISSUE TITLE
Final Fantasy Tactics A2 - .strm files don't seem to loop properly

### ISSUE THREAD

**Issue by kode54** [losnoco/vgmstream#107]
https://www.zophar.net/music/nintendo-ds-2sf/final-fantasy-tactics-a2-the-sealed-grimoire

125 A Time Eternal seems to loop completely, and pops loudly on each repeat. I don't know if this is the cause of a foo_upnp related crash.

@bnnm Maybe you can look at this too?

**Comment by bnnm** [comment]
I did some tests and seems if ADPCM history is preserved it sounds fine (in vgmstream.c. line 1852: vgmstream->meta_type == meta_NDS_STRM_FFTA2 ||). I'll tests some more and push it next time, if you want.

However I noticed during my tests the music doesn't seem to decode properly. It sounds ok enough but the waveform is weird. Maybe the 'pop' is more noticeable due to this.
It's using old school IMA (interleaved) but maybe it's actually some IMA variation? I tried a few things (nibble order, various nibble expansions) but I don't understand ADPCM enough to guess what is wrong. Some kind of sample scale problem, any hints?

Example (above strm, below OST version): 
![example](https://user-images.githubusercontent.com/22844311/27925839-75d3ad32-6286-11e7-8f58-cd17b37796ab.png)

**Comment by kode54** [comment]
I just wonder if there would have been a bug maybe a few dozen commits ago that would have caused this stuff to crash foo_upnp? I think more that it may be choking due to the sample rate, though, which isn't our fault.

**Comment by bnnm** [comment]
I don't think I touched anything that would affect it, but you never know. Maybe you could convert the file to .wav and try if that crashes too.
I tried foo_upnp with r1050-522 and r1050-549 locally and seemed to work, but maybe I didn't do a proper test.

**Comment by bxaimc** [comment]
The loop has always been broken. Might have something to do with the short-blocks?

**Comment by bnnm** [comment]
I've fixed various IMA bugs in the last PR and the waveform is almost correct now (still deviates slightly, different step table?) and I don't think it clicks anymore. Maybe your problem improved too?

**Comment by bnnm** [comment]
I've added Yet Another IMA that FFTA2 was using (mostly out of pride), so waveform and decoding should be 100% correct now.
