### ISSUE TITLE
ACM 1-channel files are being played like with double samplerate

### ISSUE THREAD

**Issue by alex-i-1** [losnoco/vgmstream#22]
https://github.com/kode54/vgmstream/blob/master/src/coding/acm_decoder.c line 675 :  'acm->info.channels = 2;'.
This forcing is not good - it is against the purposes of the values in the header.
Even if would appear that the major of sounds have this value incorrect, this is, in my opinion, not the proper way to resolve that situation - the proper way would be to make correction only for those sounds which have this value incorrect.
Test sound :  http://a0.sderni.ru/d/2101408/_pb_faster_15A91B17.7z

**Comment by kode54** [comment]
@bnnm @NicknineTheEagle Anyone care to run some tests on this?

**Comment by NicknineTheEagle** [comment]
I've never worked with ACM files so I don't think I would be of much help.

**Comment by kode54** [comment]
Sorry, didn't think of that. I should ask if anyone else on hcs64.com knows about the issues we still have open.

**Comment by bnnm** [comment]
I checked this before, many music ACM set channels to 1 even though they must use 2. I guess we could do some heuristics to detect it, but I don't have any 1ch ACM to test, so until then we could leave this open.

Also apparently most sfx ACM come inside a "WAVC" header that properly specifies channels too.

**Comment by bnnm** [comment]
Ok, updated libacm (no decoding differences but the API is nicer), and added support for ACM with "WAVC" header (sfx) as .wavc (header id). WAVC sets channels correctly, and seems used for sfx in all games except Fallout 1 (and 2?), which use plain ACM.

In Fallout you can find mono ACM with 2 in "channels", and stereo ACM with 1. That value looks related to ACM quality (rows/cols) and isn't channels at all.

I tried a few ideas but I don't think it's possible to detect channels. We want music, so by default it'll always play plain .ACM (not .WAVC) as 2ch. As a hack/compromise, if plain .ACM (not WAVC) is renamed to .wavc it plays as 1ch, so you can force Fallout 1ch sfx to play.


So that's all we can do and this can be closed I think.

[wavc-acm-1ch.zip](https://github.com/kode54/vgmstream/files/2366871/wavc-acm-1ch.zip)
