### ISSUE TITLE
EAAC: Proper loop handling needed [Need for Speed: World (PC)]

### ISSUE THREAD

**Issue by NicknineTheEagle** [losnoco/vgmstream#256]
This is a similar issue to EA-XMA one, the music tracks from NFS: World are in EALayer3 v2 "PCM" and some of them only play the first few seconds and then stop. Strangely, this doesn't happen with all the tracks. Here are all the music files:
https://www65.zippyshare.com/v/EvpQFL43/file.html

**Comment by bnnm** [comment]
Some blocks have padding, which I didn't expect (though I should have, EA being EA and all), so the decoder gets confused. Sigh. I need to give some long thought about how to deal with that.

They also use the 0x80 flag even though there is more data, not cool. I take it that the set was properly extracted?

**Comment by NicknineTheEagle** [comment]
Oh, boy, this sounds fun. The game stores music as raw SNR/SNS files so they should be fine.

**Comment by NicknineTheEagle** [comment]
Oh, I think I got it, these are looping sounds with "intro" and "body" parts. [Zenchreal's tool](https://bitbucket.org/Zenchreal/ealayer3/src) can handle them, saving the "body" as "name.part2.wav".

**Comment by NicknineTheEagle** [comment]
The second long is "body" offset, not sure what the first one is. Maybe number of samples in the intro?

**Comment by bnnm** [comment]
I think the header has full num_samples = single file, and has the loop flag.
Maybe 0x08=loop start samples, 0x0c=loop start offset. I've only seen files looping from start to end so maybe this is what EAAC normally does when using loops.

**Comment by NicknineTheEagle** [comment]
Yeah, that certainly makes sense. That would also explain non-streamed looped sounds - they only have one 1 int after the header and I've only seen it as 0. Since non-streamed samples are stored as one block it's likely loop start sample.

**Comment by NicknineTheEagle** [comment]
I suggest you centralize SNS blocked layout handling code somehow, with all these new rules it's gonna become bothersome to maintain.

**Comment by NicknineTheEagle** [comment]
Wait, the padding doesn't separate those blocks, it's *inside* the last intro block. That's just great.

**Comment by NicknineTheEagle** [comment]
Any progress on this?

**Comment by bnnm** [comment]
These kind of issues I give thought at random times for a while, thinking of various solutions' pros and cons, until I'm (somewhat) satisfied with one.

So nothing tangible for now, but I can post ideas and considerations, if you want.

**Comment by NicknineTheEagle** [comment]
Speaking of EALayer3, is there a reason we use libmpg123 and not ffmpeg for MP2/MP3 decoding?

**Comment by NicknineTheEagle** [comment]
Why use third party libraries in the first place? I can understand using libvorbis cause that's the official library from Xiph.org but FFmpeg is a community project like ours. Wouldn't handling the code would be easier if all the decoders were in our code?

**Comment by bnnm** [comment]
If you mean "why vgmstream doesn't have an MP3 decoder (or any other) directly here instead of using DLLs", it'd be nice, but would take a lot of effort.

I for one don't know much about MDCT (MP3/XMA/ATRAC3/etc) decoders, so making a new one or modifying existing ones for fixes or features we need would be very hard, since those decoders are huge. Plus other projects' licences may object about code usage and IANAL.

That's lots of time I could devote to making more decoders or parsers instead. If the decoder is simple enough I do try to include directly (ex. EA-MT), since even linking to new DLLs is a pain but I do what I can and take a pragmatic approach.

**Comment by kode54** [comment]
I do agree about using separate libraries instead of FFmpeg, though. Maybe it would be beneficial to try to make the decoders support both the dedicated libraries, or use FFmpeg instead if that's configured.

**Comment by bnnm** [comment]
I've fixed this in the next PR, though I'm not too happy how the code turned out (see the comment), but it works at least.

**Comment by NicknineTheEagle** [comment]
https://github.com/kode54/vgmstream/blob/7840d9df1f0ba0d49e3ccb40877b5b96f4a106b8/src/meta/ea_eaac.c#L632-L638
Should only use this for streamed sounds cause RAM sounds aren't blocked.

**Comment by bnnm** [comment]
I don't think RAM sounds can trigger loop_start > 0 though? (get_snr_size would fail?). Even if they did it should work, since it passes the streamed flag and restricts sizes per segment.

The clicks are, I believe, unrelated to looping. Basically I don't understand how discard modes actually work ([see here](https://github.com/kode54/vgmstream/blob/master/src/coding/mpeg_custom_utils_ealayer3.c#L589)), and this affects all EAL3, noticeable in looped files. 

Zench's ealayer3.exe seems to discard one extra frame, but if you join the 2 sections it creates there is still a minor glitch when looping. Since I can't really compare the output with real EA tools I'm not sure what to do. Wouldn't NFS:World include some ealayer3.dll or audio dll (or main .exe anyway) that you could post?

**Comment by NicknineTheEagle** [comment]
Some sounds from FIFA 08 (PS3) are RAM sounds with loop_start set to 12. build_segmented_eaaudiocore_looping fails because it tries to set up two segments while there's only one block and loop_start_offset is not set.

**Comment by bnnm** [comment]
I'll fix it for the next version, but those FIFA 08 abks are a bit strange. After decoding they are missing a chunk of audio towards the end, but offsets are ok and the eaac streamfile is demuxing correctly as far as I can tell. Maybe also related to discard stuff?

**Comment by NicknineTheEagle** [comment]
Looks like we got this fully covered now.
