### ISSUE TITLE
Audacious plugin does not build

### ISSUE THREAD

**Issue by kargaroc** [losnoco/vgmstream#317]
OS: Arch Linux (up-to-date)

When attempting to build the Audacious plugin (following /doc/BUILD.md), the linker complains about missing libraries even when all the dependencies are installed

```
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `ue4_opus_get_encoder_delay'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `free_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `decode_ogg_vorbis'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `free_ogg_vorbis'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `mpeg_bytes_to_samples'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `init_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `decode_vorbis_custom'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `seek_ogg_vorbis'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `reset_ogg_vorbis'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `init_vorbis_custom'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `init_mpeg_custom'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `reset_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `decode_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `reset_vorbis_custom'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `flush_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `seek_mpeg'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `free_vorbis_custom'
/usr/bin/ld: ../src/.libs/libvgmstream.so: undefined reference to `seek_vorbis_custom'
```

**Comment by bnnm** [comment]
I think some scripts broke after [this PR](https://github.com/kode54/vgmstream/pull/163/commits/bc455672084a495679e399017745a1de0ac0e2bf).

I don't know much about linux/audacious/autotools, and it's a lot of effort for me to setup/test, so it may take a while to fix. I remember I had trouble building after that commit, but was able to copy the the old makefiles to get it working, so that could give you a start.

**Comment by Josephvb10** [comment]
Yup, same problem

**Comment by Josephvb10** [comment]
BTW it compiled fine using the AUR package: https://aur.archlinux.org/packages/vgmstream-kode54-git/

Worth checking the patches in there for the Makefiles.

`+include_HEADERS = ../ext_includes/clHCA.h
+__vgmstream_includedir = $(includedir)/vgmstream
+__vgmstream_include_HEADERS = vgmstream.h streamfile.h util.h streamtypes.h
+__coding_includedir = $(includedir)/vgmstream/coding
+__coding_include_HEADERS = coding/g72x_state.h coding/nwa_decoder.h
+`

**Comment by xogium** [comment]
Nop, still the same.
Here is a full build log.

By the way the arch aur package is failing here also, but not with the same error, something related to a patch not applying.
http://ix.io/1v7m
Thanks !

**Comment by kode54** [comment]
It would appear that the VGM_USE_VORBIS and VGM_USE_MPEG command line definitions aren't propagating to at least a few of the subdirectories worth of Makefiles. And why aren't any of the other libraries, including FFmpeg, being defined as well?

**Comment by bnnm** [comment]
I think I got it working, can you try this?

- go to [src/coding/Makefile.autotools.am](https://github.com/kode54/vgmstream/blob/master/src/coding/Makefile.autotools.am) and paste this at the end:
```
if HAVE_VORBIS
if HAVE_VORBISFILE
AM_CFLAGS += -DVGM_USE_VORBIS
endif
endif
if HAVE_LIBMPG123
AM_CFLAGS += -DVGM_USE_MPEG
endif
```
- go to [src/Makefile.autotools.am](https://github.com/kode54/vgmstream/blob/master/src/Makefile.autotools.am) and change line 14:
```
-libvgmstream_la_LIBADD = $(AUDACIOUS_LIBS) $(GTK_LIBS) -lm
+libvgmstream_la_LIBADD = -lm
```
- rebuild and after `sudo make -f Makefile.autotools install` do: `sudo ldconfig`
- start audacious in verbose mode to check if it was installed correctly: `audacious -V` (it will complain about not finding libvgmstream.so.0 if it wasn't)

That seemed to work for me, if it works for you I'll do a PR.


FFmpeg and other libs require various build changes to enable I don't know how to do in autotools (for example, normally you'd want a trimmed ffmpeg build rather than link against the standard one, but I don't know anything about Linux+autotools standard commands/dirs/libs/links/etc). That Arch package Josephvb10 posted is worth studying I guess.

**Comment by kode54** [comment]
I don't know that they'd want a "trimmed" FFmpeg build at all, since they can just link against the one that comes from installing their distribution's FFmpeg package. Or does that not come with a convenient bundle of dynamic libraries? I wasn't quite sure that any of the libraries we use need to be bundled with VGMStream on Linux. Well, unless the stable release of FFmpeg is so far behind that the stuff we use will be horribly broken without a bleeding-edge Git version.

**Comment by xogium** [comment]
Yeah, for ffmpeg it is quite up to date:

```

ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831

```
I think we could simply rebuild vgmstream against new ffmpeg version if need be, dynamic linking and all.
I will try the makefile modifications right now.
Thanks !

**Comment by kode54** [comment]
It may not have the latest changes that bnnm worked so hard to get upstream, but those may be coming soon.

**Comment by xogium** [comment]
Yep, it appears to work just fine with those modifications to both makefiles.
Yeepi !
Was a pain to make a windows vm just to listen videogame musics. :tada:

**Comment by bnnm** [comment]
Ok, I've pushed the changes.

vgmstream assumes latest, trimmed FFmpeg for some things (xma gapless, libopus, etc), and audacious has a FFmpeg plugin too (so who knows how extensions would clash), but ignoring that it could be linked to the global one I guess.

It's just I don't know which changes are needed (since configure.ac must be told about FFmpeg... I think), and I don't use Linux so it's a lot of effort to investigate/test, and I'm not familiar with their procedures to begin with (here I learnt installing shared libs to a global libdir was a thing). But anybody is welcome to fix the docs and builds.

**Comment by bnnm** [comment]
This should work now.
