### ISSUE TITLE
Choppy output from vgmstream on raw ADPCM file

### ISSUE THREAD

**Issue by BattleDash** [losnoco/vgmstream#490]
Hey there, I'm trying to convert some raw ADPCM files to WAV, the only way I've found this possible so far is with vgmstream. However while it technically works the output is extremely choppy and I can't find any useful command line options to fix it. Any help is appreciated!

[Original ADPCM file](http://www.mediafire.com/file/hkp5f7e2l3ponpn/Event_NightNight_Music_02.ADPCM/file)

[What I got when put through vgmstream](https://www.mediafire.com/file/7vbhvknru2w1hxp/Event_NightNight_Music_02.ADPCM.wav/file)

**Comment by bnnm** [comment]
Please post a bunch of files and the name of the game and possibly how was extracted. Otherwise it's really hard to do anything.

I take it's some UE4 game file (not raw but just a .wav with another extension), but wavs are a bit special in UE4 so it would need extra detection based on more files to make it playable (no regular player will handle those).

**Comment by BattleDash** [comment]
Sorry about getting back to you late on this, I got help up.
Game: Fortnite
Extracted With: uModel
Engine: UE4
Files: https://dash.cool/adpcm.zip

**Comment by bnnm** [comment]
Fixed, detection is a bit complex so post if you find other files playing wrong.
(foobar plugin may take a bit to be updated).

**Comment by BattleDash** [comment]
Works perfectly, thanks!
