### ISSUE TITLE
Frostbite EAAC Looping

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [losnoco/vgmstream#496]
Okay so Frostbite games use audio "segments" defined by blueprints in the game files but it is possible to loop audio without the use of that information.
Each audio segment in one chunk file has a "SamplesOffset" value that is just a decimal offset for the segment in the chunk. The segment is basically a separate file stuck to the end of the first so maybe searching the file for other headers could work.
[MP_Rotterdam_Music_PreEOR_6ch.zip](https://github.com/losnoco/vgmstream/files/3790085/MP_Rotterdam_Music_PreEOR_6ch.zip)
Here's a sample from Battlefield V.
SamplesOffset is 6163392.

**Comment by NicknineTheEagle** [comment]
Frostbite chunks are not meant to be used directly and are not supported by vgmstream. All assets in Frostbite are accessed via EBX files, so you're supposed to use EBX files to acquire information on segments and loops.

**Comment by CosmicDreamsOfCode** [comment]
FB sounds do work in vgmstream. Just gotta rename the chunk to .sps and they load just fine but without looping.

**Comment by NicknineTheEagle** [comment]
Frostbite chunks often contain multiple sound files pasted together each of which may or may not be preceded by a seek table. You should not and often cannot use them directly. Use EBX files to separate chunks into separate SPS files.

**Comment by bnnm** [comment]
As mentioned those are just 2 .sps pasted together and not a real format. Other EA formats paste two or more unrelated .sps too, so it doesn't make sense for vgmstream to loop those since it would be wrong in most cases.

Like Nicknine says you should split the .sps with a proper extractor then use [TXTP](https://github.com/losnoco/vgmstream/blob/master/doc/TXTP.md#segments-mode) to play segments. EAAC can contain looping info if the dev wants, btw.

 Plus, if you need to rename to get it playing there is a good chance that's not a proper .sps and I can't guarantee that trick will work in next versions.
