### ISSUE TITLE
Mass Effect PS3 - ISB - need help determining sony codec used

### ISSUE THREAD

**Issue by Mgamerz** [losnoco/vgmstream#560]
First off, thank you for this, this program is amazing and tons of hard work look like it has gone into it. I'm a toolset dev for the ME1/2/3 scene and I know how awful working with audio formats can be (ugh... don't even get me started on wwise)

The PS3 version of ME1 has a lot of additional audio that is unused that I am trying to extract. Your ISB implementation is pretty accurate to the one from psychonauts and me3explorer.

In ISB it has codecs listed, on PC it uses 0x0-0x2, but on PS3 it has a codec of 0x5, which is not supported in this program. I've done the work to get the parser working for PS3 files, I'm just not sure what codec was used (or how to find out) - the header for the data segment is MSFC, which from googling is MSF Codec. VGMStream has support for it but I am not sure which one to use, and after trying many for hours I could not find one that worked, i'm wondering if you could help me out.

I've made a fork and committed the code to load PS3 ISB files: https://github.com/ME3Tweaks/vgmstream/commit/6257f474fa7db7d983b0b013254185391a3514be#diff-896edb6e6044cb5936ac2e96b6e4c638

Specifically the switch statement for 0x5: https://github.com/ME3Tweaks/vgmstream/commit/6257f474fa7db7d983b0b013254185391a3514be#diff-896edb6e6044cb5936ac2e96b6e4c638R177

And here are some ISB files for reference:
[ISACT.zip](https://github.com/losnoco/vgmstream/files/4216621/ISACT.zip)

These are the same audio banks from the PS3 version of ME1 and the PC version. They contain the same audio. 

Some of the audio banks in ME1 PS3 work because the ISB parser fails and it fails over onto ffmpeg which works. However not all of them do, and there are a lot of unused ones I am interested in. I don't think this is a hard problem but I am still somewhat new to C++ and I am not really that good with audio codecs even though I've spent dozens of hours on them.

One other thing - the ISB parser in vgmstream does not extract past the first file in the ISB bank. I could easily fix this (... i think) but I didn't want to clutter my commits with it. Essentially once you finish the header you would just loop again and again and keep extracting until the end of the file. Currently it finds all of the files and then extracts only the first one. You can see many of them parsed with ME3Explorer on PC version for example:
![image](https://user-images.githubusercontent.com/2738836/74691171-f9737f00-519e-11ea-93cb-4aa6c7471217.png)

Thanks for the work you do on this. I'll be looking into wwise next for ME2 :)

**Comment by AnonBaiter** [comment]
vgmstream has a "subfile" feature within its code that can let you pick out a part of an "audio stream" by setting up the offset, size and the extension of the stream you want to pick up.

in this case, this MSFC you keep wondering about as if it's some sort of mysterious figure isn't an "MSF Codec". it's an actual format container that could store just about anything else, including audio which is where vgmstream's focus is at. they are usually stored with an **_msf_** extension. the actual codec used for this one is the LAME MP3 codec, stored into a MSFC format because said format has been designed for usage into PS3 games.

so, since these are MSFC files you're trying to deal with within an isb file, you can use up the "subfile" feature. here's an example:
https://github.com/losnoco/vgmstream/blob/master/src/meta/nus3bank.c#L151-L228

do keep in mind however that what i'm suggesting is a temporary solution and may not even stick out well in the following years but if you're in doubt i'll just leave this here:
```
temp_sf = setup_subfile_streamfile(streamFile, subfile_offset, subfile_size, "msf");
if (!temp_sf) goto fail;</p>
```
```
vgmstream = init_vgmstream_msf(temp_sf);
if (!vgmstream) goto fail;
break;
```

as for audio extraction, i couldn't find anything that could match what you're looking for.

in any case, paging @bnnm.

**Comment by Mgamerz** [comment]
Thanks for that info, that works, mostly. There is significant audio cutoff which sometimes results in less than half of hte original audio available, but this is definitely better than nothing. I'm now investigating the SoundNodeWave format for ME1, which on PC seems to use ISB Codec ID 4 (which is not listed at all). It doesn't have a magic following data, which makes me think this is a codec stream (not sure of the terminology, maybe sample data?) rather than a container format like you mentioned.

**Comment by bnnm** [comment]
Regarding MSF, easiest would be the "subfile" feature as suggested (or you'd need to parse MSF again). Cut songs may be a wrong subfile_size, or some unusual MSF usage, or a bug in the MSF parser, if you could point to some examples.

For data past the first file, vgmstream already supports as "subsongs". foobar2000 or winamp 'unpack' all subsongs automatically, but with test.exe needs the `-s N` command (by design). If you want to use vgmstream's code as a "plugin" see [here](https://github.com/droidmjt/Droidsound/issues/408) how subsongs should be handled.

Codec 4 is probably XMA fmt chunk + raw XMA data, see other formats calling [these functions](https://github.com/losnoco/vgmstream/blob/5ea57c08d60a03e704097d0203ac5a608e5e70fc/src/coding/coding.h#L366). The XMA fmt is likely in the "cmpi" chunk, or right before raw XMA data, but could be hard to 'get' if you haven't dealt with XMA before. I could implement with some examples, if you prefer. Note that SoundNodeWave is just a UE3 class/container and you should be extracting/handling the actual ISB inside.

Some suggestions if you plan to submit your changes:
- should use C89 style, that is, variables declared at the beginning of `{ .. }` blocks, preferably in `lower_case`.
- 4 white spaces instead of tabs
- BE/LE handling it's usually done with function callbacks [like this](https://github.com/losnoco/vgmstream/blob/5ea57c08d60a03e704097d0203ac5a608e5e70fc/src/meta/wwise.c#L64).

As for wwise, every .wem variation should be supported by vgmstream, though event data (when and how audio is triggered) is usually in .bnk in a complex format.

**Comment by Mgamerz** [comment]
Thanks. I do plan to do a PR, but I want to get it working on my end as I
want to find a way to play audio back in our ME3Explorer toolset without
having to write to disk. Something like reading a binary blob from stdin
(the files are sometimes compressed so I cannot simply just tell it to read
an existing on file disk, we decompress it in memory in our c# toolset).

I do have some examples I can get you later today. The UE3 Soundnodewave
classes for mass effect 1 does not appear to be the same as stock ue3. It
uses Xbox ima codec for most audio, stored also in isb. The audio stored in
these object exports is still isact, with the UE3 property headers. We have
that all parsed out so slicing out the individual files (by riff header
scans) is how I planned to do it, it's how we do the vorbis versions now.

My modding scene is looking forward to me poking around your wwise code and
seeing what we can implement into our scene for me2 and 3. There is at
least one codec used we don't understand and they will be happy once I use
your tools to find out what it is because have just been guessing for
years. The audio mixing and bank format though... Gonna guess we never
figure that out.

Still, thanks for your work on this, this is incredible. Gives me hope we
will finally be able to advance our audio editing capabilities for our
series of games with your tremendous amount of work you've all done.

**Comment by Mgamerz** [comment]
Here is an ISB (embedded in SoundNodeWave binary data) that I extracted and trimmed to match a RIFF file. 

[ice50_retract_rods.zip](https://github.com/losnoco/vgmstream/files/4222704/ice50_retract_rods.zip)

Metadata about the audio:
![2020-02-18_18h38_34](https://user-images.githubusercontent.com/2738836/74793908-02d41880-527f-11ea-9699-56a5cc258910.png)

It uses Codec ID 4, which you can see at 0x310.

**Comment by AnonBaiter** [comment]
Codec ID 4 is basically just raw XMA audio stream with about 32 bytes of "fmt"-like header data. deftly needs to be parsed.

0x00 - either 0x165 or 0x166
0x02 - bit depth
0x04 - 0x10d6, can be skipped
0x06 - zero
0x08 - number of layers
0x0a - 2, can be skipped
the rest is just a listing of layer info that encompasses the entirety of an XMA stream since XMA-encoded files are handled into either mono or stereo "layers". i had to figure this out myself since vgmstream's current code handles RIFF XMA headers rather differently from my observations.

**Comment by Mgamerz** [comment]
I've refactored a significant portion of my toolset tonight with the new info I've learned from this project. As a result I've been able to do multiple things:

1) Calculate stream length of audio samples without loading them into a parser (I do the work myself now)
2) Can now play PCM raw samples because I know how to get teh right info from ISB header

I wrote scanner for ME1, these sound node waves use codec ID 0 1 2 4 on PC. 0 PCM seems very rare (almost like the devs mistakenly chose it), 1 is mostly for sound effects (Xbox IMA), 2 is used for just about all lengthy sounds like audio, 4 (XMA1?) is used in several places but no idea why. 5 is used on PS3 version of the game for some stuff.

I can get you some samples of Codec 1 and 4 now that I rebuilt my tools to make this process easier if it would help.

**Comment by bnnm** [comment]
If you paste this in the `switch` you should get XMA playing:
```
#ifdef VGM_USE_FFMPEG
        case 0x04: {
            uint8_t buf[0x100];
            size_t bytes;
            off_t fmt_offset = start_offset;
            size_t fmt_size = 0x20;

            start_offset += fmt_size;
            stream_size -= fmt_size;

            /* XMA1 "fmt" chunk (BE, unlike the usual LE) */
            bytes = ffmpeg_make_riff_xma_from_fmt_chunk(buf,sizeof(buf), fmt_offset,fmt_size, stream_size, streamFile, 1);
            vgmstream->codec_data = init_ffmpeg_header_offset(streamFile, buf,bytes, start_offset, stream_size);
            if (!vgmstream->codec_data) goto fail;
            vgmstream->coding_type = coding_FFmpeg;
            vgmstream->layout_type = layout_none;

            vgmstream->num_samples = pcm_bytes / channel_count / (bps/8);
            xma_fix_raw_samples(vgmstream, streamFile, start_offset, stream_size, fmt_offset, 1,1);
            break;
        }
#endif
```
No need to post codec 1, I have a bunch and should be playing ok. PC files with codec 4 are surely a leftovers, as AFAIK Microsoft never allowed XMA in PC (they had WMAPro that is mostly the same).

**Comment by Mgamerz** [comment]
Ah sorry, I did have codec 1 working, the only thing not working was my
brain at 2am :)

I'll take a look at this tonight. Really appreciate your help! I don't know
if these are even used by game will never know until I can hear them :)

**Comment by bnnm** [comment]
Added these codecs to isb.c, since they were kinda pending.

**Comment by ZippyZolton** [comment]
I would hate to necro a closed issue, but I'm trying to do the same thing with the TikGames version of HamsterBall, its .snd files have the MSFC header but import into Audacity perfectly fine. I don't know what way I should export to get it working fine in-game. Is there any way you can help me?
(example file ripped from the game) [f92a1960.zip](https://github.com/vgmstream/vgmstream/files/15143654/f92a1960.zip)

**Comment by mirh** [comment]
I understand that vgmstream is just about decoding, it has no "export back" feature. 

I guess you can take a look at how OP eventually figured something out, but even that still has to go through the original ISACT
https://github.com/ME3Tweaks/LegendaryExplorer/wiki/Editing-LE1-Audio
https://github.com/ME3Tweaks/LegendaryExplorer/blob/Beta/LegendaryExplorer/LegendaryExplorerCore/Sound/ISACT/ISACTHelper.cs
